name: streamlit-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - streamlit>=1.35.0
    - Authlib>=1.3.2
    - pyarrow>=14.0.0
    - pdfplumber==0.9.0
    - python-docx==1.0.1
    - PyPDF2>=3.0.0
    - spacy>=3.7.4
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.1/en_core_web_sm-3.7.1.tar.gz#egg=en_core_web_sm
    - sentence-transformers>=2.2.2
    - torch>=2.1.0
    - scikit-learn==1.2.0
    - nltk==3.8.1
    - fpdf2==2.7.0
    - python-magic==0.4.27
    - supabase>=2.0.0
    - language-tool-python>=2.7.1
