cookie:
  expiry_days: 30
  key: ats_scorer_secret_key_12345
  name: ats_scorer_auth
credentials:
  usernames:
    demo_user:
      email: demo@example.com
      name: Demo User
      password: $2b$12$Xhon4m8SOiatT9SCWG.VCOBhYanKN4nFSWbwLh3cnOsCMgpLdcp6.
    test_user:
      email: test@example.com
      name: Test User
      password: $2b$12$myTB54dzaqktvS7T.sZEE..1R3iv3BLb3EWm7Vgd5XFV3I5RGFCP6
preauthorized:
  emails: []
